version: '3.8'
services:

  mysql:
    networks:
      - ci
    environment:
      MYSQL_ROOT_PASSWORD: "passwordasd"
      MYSQL_DATABASE: "laravel"
      MYSQL_USER: "asdasdasd"
      MYSQL_PASSWORD: "zxczxczx"

  php:
    networks:
      - ci
    volumes:
      - .:/var/www/html/
    working_dir: /var/www/html/
    environment:
      AUTORUN_ENABLED: false
    depends_on:
      - mariadb

  node:
    image: node:20
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app/
    networks:
      - ci

  mailpit:
    image: axllent/mailpit
    networks:
      - ci

networks:
  ci:
